import React from 'react'

export default function Home() {
  return (
    <>
      <h1 className='h1-sm font-sans text-white text-2xl font-extrabold my-4 mx-10 p-5 text-center w-3/4 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 border rounded-3xl'>The Home Section</h1>
      <div className='flex flex-col  w-4/5 mx-2 p-sm bg-white'>
        <p>
          <strong> These text is randomly generated by HTML Ignore This Text </strong> <br />

          ipsa veniam rem repellat, eos eum? Minus nemo, neque exercitationem quos id similique aut magnam veniam reiciendis nostrum debitis ipsam corporis optio. Odio excepturi quos nihil ullam consectetur labore officiis eligendi expedita assumenda. Nisi dolor nam porro. Facere labore recusandae repellendus, accusamus animi architecto hic dignissimos sit eos sed blanditiis id ea molestias autem impedit ullam pariatur? Voluptatibus veritatis iure placeat voluptate officiis repudiandae praesentium quisquam neque ad velit quibusdam, iusto maxime minima unde doloribus dolores hic eaque eum sapiente! Voluptatum veritatis aperiam aut? Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam fugit sequi maiores molestiae maxime eveniet qui voluptates non consectetur quam animi autem ratione in, voluptatem, quis quibusdam nihil recusandae? Rem, autem a cumque itaque debitis perferendis ratione quod sed mollitia sint doloribus delectus </p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus laudantium perferendis molestiae rerum qui dolorum ipsa culpa. Laborum facere fugiat sit mollitia. Minus quam ratione nulla cum adipisci quos dolorum commodi pariatur, eius, delectus excepturi numquam blanditiis similique nostrum, labore consequuntur porro fugit voluptatem? Officia ad repudiandae ex, alias officiis facere hic ipsa inventore libero consequuntur aliquam ipsam at perspiciatis dolorum dolorem nesciunt non quibusdam exercitationem autem dolore quis voluptates possimus et! Fugit deleniti impedit officia eum eveniet adipisci, corrupti, facilis, asperiores assumenda natus in temporibus sit modi quibusdam dolorum error. Eveniet dolore enim eaque dolorem, quas tempore dolorum neque!</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus laudantium perferendis molestiae rerum qui dolorum ipsa culpa. Laborum facere fugiat sit mollitia. Minus quam ratione nulla cum adipisci quos dolorum commodi pariatur, eius, delectus excepturi numquam blanditiis similique nostrum, labore consequuntur porro fugit voluptatem? Officia ad repudiandae ex, alias officiis facere hic ipsa inventore libero consequuntur aliquam ipsam at perspiciatis dolorum dolorem nesciunt non quibusdam exercitationem autem dolore quis voluptates possimus et! Fugit deleniti impedit officia eum eveniet adipisci, corrupti, facilis, asperiores assumenda natus in temporibus sit modi quibusdam dolorum error. Eveniet dolore enim eaque dolorem, quas tempore dolorum neque!</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus laudantium perferendis molestiae rerum qui dolorum ipsa culpa. Laborum facere fugiat sit mollitia. Minus quam ratione nulla cum adipisci quos dolorum commodi pariatur, eius, delectus excepturi numquam blanditiis similique nostrum, labore consequuntur porro fugit voluptatem? Officia ad repudiandae ex, alias officiis facere hic ipsa inventore libero consequuntur aliquam ipsam at perspiciatis dolorum dolorem nesciunt non quibusdam exercitationem autem dolore quis voluptates possimus et! Fugit deleniti impedit officia eum eveniet adipisci, corrupti, facilis, asperiores assumenda natus in temporibus sit modi quibusdam dolorum error. Eveniet dolore enim eaque dolorem, quas tempore dolorum neque!</p>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus laudantium perferendis molestiae rerum qui dolorum ipsa culpa. Laborum facere fugiat sit mollitia. Minus quam ratione nulla cum adipisci quos dolorum commodi pariatur, eius, delectus excepturi numquam blanditiis similique nostrum, labore consequuntur porro fugit voluptatem? Officia ad repudiandae ex, alias officiis facere hic ipsa inventore libero consequuntur aliquam ipsam at perspiciatis dolorum dolorem nesciunt non quibusdam exercitationem autem dolore quis voluptates possimus et! Fugit deleniti impedit officia eum eveniet adipisci, corrupti, facilis, asperiores assumenda natus in temporibus sit modi quibusdam dolorum error. Eveniet dolore enim eaque dolorem, quas tempore dolorum neque!</p>

      </div>
    </>
  )
}
